{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "c96ac3fa1578e415",
   "metadata": {
    "collapsed": false
   },
   "source": [
    "Vamos testar algumas técnicas para tentar incrementar o resultado obtido no primeiro estudo. Para isso, vamos testar o desempenho de outros modelos  e tentar ajustar seus parâmetros. No TCC de Mayara, ela obteve um bom resultado utilizando Naive Bayes. Para ajuste de parâmetros, acho que vale a pena testar o parâmetro C do LinearSVC para valores um pouco mais altos, utilizar a parametrização L2 e testar também a regressão logística, também com valores altos para o parâmetro C.\n",
    "\n",
    "Ao tentar melhorar o desempenho, creio que não faz sentido utilizar o parâmetro pre-punning, uma vez que o modelo não está sofrendo *overfitting*, penso que lidar apenas com o número de estimators seja suficiente.\n",
    "\n",
    "O algoritmo *Random Forest* busca diminuir o *overfitting* da *Decision Tree* medindo o desempenho de várias árvores. Como nossos modelos não estão sofrendo disso, talvez um menor número de estimadores tenha um desempenho melhor. Vamos testar.\n",
    "\n",
    "Acho que uma opção é verificar os atributos mais importantes, selecionar apenas esses e remover a aleatoriedade dos atributos no treinamento da *random forest*.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "initial_id",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2023-10-25T02:25:00.026719Z",
     "start_time": "2023-10-25T02:24:38.659567200Z"
    },
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "import pickle\n",
    "import os\n",
    "import spacy\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from spacy.cli.download import download\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.model_selection import GridSearchCV\n",
    "from sklearn.metrics import classification_report"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "6bd8299ab7b7c286",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2023-10-25T02:25:00.039133600Z",
     "start_time": "2023-10-25T02:25:00.035126400Z"
    },
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "def fazer_amostragem(train_dataset: pd.DataFrame):\n",
    "    \"\"\"\n",
    "\n",
    "    :param train_dataset:\n",
    "    :return:\n",
    "    \"\"\"\n",
    "    sentimentos = train_dataset['Sentimento'].unique()\n",
    "    df = pd.DataFrame([])\n",
    "\n",
    "    for sentimento in sentimentos:\n",
    "        df_filtrado = train_dataset.loc[train_dataset['Sentimento'] == sentimento][:600]\n",
    "        df = pd.concat([df, df_filtrado])\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "def ler_modelo(path: str):\n",
    "    return pickle.load(open(path, 'rb'))\n",
    "\n",
    "\n",
    "def salvar_modelo(path: str, modelo):\n",
    "    return pickle.dump(modelo, open(path, 'wb'))    \n",
    "\n",
    "\n",
    "def criar_embeddings(df_tweets):\n",
    "    try:\n",
    "        nlp = spacy.load('pt_core_news_lg')\n",
    "    except (IOError, OSError):\n",
    "        download('pt_core_news_lg')\n",
    "        nlp = spacy.load('pt_core_news_lg')\n",
    "    # desativamos todos os outros pipes que vem com o modelo nlp porque não preicsaremos deles\n",
    "    with nlp.disable_pipes():\n",
    "        # transformamos cada texto em um vetor e colocamos em uma array\n",
    "        print('Fazendo os word embeddings')\n",
    "        vetores = np.array([nlp(texto).vector for texto in df_tweets.Texto])\n",
    "\n",
    "    return vetores"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "bc2377e264d747d4",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2023-10-25T02:25:00.559306Z",
     "start_time": "2023-10-25T02:25:00.044139900Z"
    },
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "path_datasets = '../resources/datasets'\n",
    "\n",
    "# importação dos dados\n",
    "df_treinamento = pd.read_csv(\n",
    "    f'{path_datasets}/tweets_ekman.csv',\n",
    "    usecols=['Texto', 'Sentimento']\n",
    ").dropna()\n",
    "df_alvo = pd.read_csv(f'{path_datasets}/tweets_pandemia.csv')\n",
    "\n",
    "x_trainval, x_test, y_trainval, y_test = train_test_split(\n",
    "    df_treinamento,\n",
    "    df_treinamento['Sentimento'],\n",
    "    test_size=0.2,\n",
    "    random_state=42\n",
    ")\n",
    "\n",
    "x_train, x_valid, y_train, y_valid = train_test_split(\n",
    "    x_trainval,\n",
    "    y_trainval,\n",
    "    random_state=42\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "1c57274b664cadea",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2023-10-25T02:25:01.519735500Z",
     "start_time": "2023-10-25T02:25:00.598056Z"
    },
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "# processamento dos dados para word embeddings\n",
    "path_embeddings_treinamento = '../resources/modelos/embeddings_treinamento_val.pkl'\n",
    "path_embeddings_teste = '../resources/modelos/embeddings_teste_grid.pkl'\n",
    "\n",
    "if os.path.exists(path_embeddings_treinamento):\n",
    "    embeddings = ler_modelo(path_embeddings_treinamento)\n",
    "else:\n",
    "    embeddings = criar_embeddings(x_train)\n",
    "    salvar_modelo(path_embeddings_treinamento, embeddings)\n",
    "\n",
    "if os.path.exists(path_embeddings_teste):\n",
    "    embeddings_teste = ler_modelo(path_embeddings_teste)\n",
    "else:\n",
    "    embeddings_teste = criar_embeddings(x_test)\n",
    "    salvar_modelo(path_embeddings_teste, embeddings_teste)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "46835693ca05bdd2",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2023-10-25T02:25:01.529499Z",
     "start_time": "2023-10-25T02:25:01.524486700Z"
    },
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "logreg = LogisticRegression(random_state=0, n_jobs=-1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "5d2973ee4c9ac5f0",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2023-10-25T02:56:37.795368800Z",
     "start_time": "2023-10-25T02:25:01.532498600Z"
    },
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py:425: FitFailedWarning: \n",
      "330 fits failed out of a total of 550.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "55 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 729, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 1152, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\linear_model\\_logistic.py\", line 1169, in fit\n",
      "    solver = _check_solver(self.solver, self.penalty, self.dual)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\linear_model\\_logistic.py\", line 56, in _check_solver\n",
      "    raise ValueError(\n",
      "ValueError: Solver newton-cg supports only 'l2' or 'none' penalties, got l1 penalty.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "55 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 729, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 1152, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\linear_model\\_logistic.py\", line 1169, in fit\n",
      "    solver = _check_solver(self.solver, self.penalty, self.dual)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\linear_model\\_logistic.py\", line 56, in _check_solver\n",
      "    raise ValueError(\n",
      "ValueError: Solver sag supports only 'l2' or 'none' penalties, got l1 penalty.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "16 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 729, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 1145, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 638, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'solver' parameter of LogisticRegression must be a str among {'newton-cholesky', 'sag', 'saga', 'lbfgs', 'liblinear', 'newton-cg'}. Got 'newton_cholesky' instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "11 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 729, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 1145, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 638, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'solver' parameter of LogisticRegression must be a str among {'sag', 'liblinear', 'newton-cholesky', 'saga', 'newton-cg', 'lbfgs'}. Got 'newton_cholesky' instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "6 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 729, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 1145, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 638, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'solver' parameter of LogisticRegression must be a str among {'newton-cg', 'liblinear', 'lbfgs', 'sag', 'newton-cholesky', 'saga'}. Got 'newton_cholesky' instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "26 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 729, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 1145, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 638, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'solver' parameter of LogisticRegression must be a str among {'newton-cg', 'liblinear', 'newton-cholesky', 'sag', 'lbfgs', 'saga'}. Got 'newton_cholesky' instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "11 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 729, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 1145, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 638, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'solver' parameter of LogisticRegression must be a str among {'lbfgs', 'newton-cholesky', 'saga', 'sag', 'newton-cg', 'liblinear'}. Got 'newton_cholesky' instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "12 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 729, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 1145, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 638, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'solver' parameter of LogisticRegression must be a str among {'lbfgs', 'newton-cholesky', 'saga', 'sag', 'newton-cg', 'liblinear'}. Got 'libfgs' instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "16 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 729, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 1145, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 638, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'solver' parameter of LogisticRegression must be a str among {'saga', 'sag', 'newton-cg', 'liblinear', 'lbfgs', 'newton-cholesky'}. Got 'libfgs' instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "16 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 729, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 1145, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 638, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'solver' parameter of LogisticRegression must be a str among {'newton-cholesky', 'lbfgs', 'newton-cg', 'saga', 'sag', 'liblinear'}. Got 'libfgs' instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "15 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 729, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 1145, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 638, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'solver' parameter of LogisticRegression must be a str among {'saga', 'sag', 'newton-cg', 'liblinear', 'lbfgs', 'newton-cholesky'}. Got 'newton_cholesky' instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "15 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 729, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 1145, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 638, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'solver' parameter of LogisticRegression must be a str among {'newton-cg', 'liblinear', 'newton-cholesky', 'sag', 'lbfgs', 'saga'}. Got 'libfgs' instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "10 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 729, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 1145, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 638, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'solver' parameter of LogisticRegression must be a str among {'sag', 'liblinear', 'newton-cholesky', 'saga', 'newton-cg', 'lbfgs'}. Got 'libfgs' instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "10 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 729, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 1145, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 638, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'solver' parameter of LogisticRegression must be a str among {'newton-cholesky', 'lbfgs', 'newton-cg', 'saga', 'sag', 'liblinear'}. Got 'newton_cholesky' instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "16 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 729, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 1145, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 638, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'solver' parameter of LogisticRegression must be a str among {'newton-cholesky', 'sag', 'saga', 'lbfgs', 'liblinear', 'newton-cg'}. Got 'libfgs' instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "25 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 729, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 1145, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 638, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'solver' parameter of LogisticRegression must be a str among {'saga', 'sag', 'liblinear', 'newton-cg', 'lbfgs', 'newton-cholesky'}. Got 'libfgs' instead.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "15 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 729, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 1145, in wrapper\n",
      "    estimator._validate_params()\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\base.py\", line 638, in _validate_params\n",
      "    validate_parameter_constraints(\n",
      "  File \"D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 95, in validate_parameter_constraints\n",
      "    raise InvalidParameterError(\n",
      "sklearn.utils._param_validation.InvalidParameterError: The 'solver' parameter of LogisticRegression must be a str among {'saga', 'sag', 'liblinear', 'newton-cg', 'lbfgs', 'newton-cholesky'}. Got 'newton_cholesky' instead.\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
      "D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\model_selection\\_search.py:979: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan 0.5952575         nan 0.59499978\n",
      " 0.59522067        nan 0.59477882        nan        nan        nan\n",
      "        nan 0.59496293        nan 0.59511026 0.59540477        nan\n",
      " 0.59477882        nan        nan        nan        nan 0.59481565\n",
      "        nan 0.5947052  0.59547842        nan 0.59477882        nan\n",
      "        nan        nan        nan 0.59485245        nan 0.59470519\n",
      " 0.59544159        nan 0.59477882        nan        nan        nan\n",
      "        nan 0.59485245        nan 0.5945579  0.59544159        nan\n",
      " 0.59477882        nan        nan        nan        nan 0.59477881\n",
      "        nan 0.59448427 0.59544159        nan 0.59477882        nan\n",
      "        nan        nan        nan 0.59477881        nan 0.59459473\n",
      " 0.59536794        nan 0.59477882        nan        nan        nan\n",
      "        nan 0.59477881        nan 0.59448427 0.59547842        nan\n",
      " 0.59481564        nan        nan        nan        nan 0.5949261\n",
      "        nan 0.59430015 0.59547842        nan 0.59481564        nan\n",
      "        nan        nan        nan 0.5949261         nan 0.59415287\n",
      " 0.59547842        nan 0.59481564        nan        nan        nan\n",
      "        nan 0.59477882        nan 0.59426333 0.59540477        nan\n",
      " 0.59481564        nan]\n",
      "  warnings.warn(\n",
      "D:\\home\\Desenvolvimento\\Analise-de-sentimentos-pandemia-covid19\\emocoes_venv\\Lib\\site-packages\\sklearn\\linear_model\\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "              precision    recall  f1-score   support\n",
      "\n",
      "      Neutro       0.96      0.95      0.96       495\n",
      "       feliz       0.71      0.72      0.71      1931\n",
      "        medo       0.54      0.61      0.57      2320\n",
      "        nojo       0.60      0.60      0.60      1648\n",
      "       raiva       0.41      0.12      0.18       562\n",
      "      triste       0.52      0.54      0.53      2097\n",
      "\n",
      "    accuracy                           0.60      9053\n",
      "   macro avg       0.62      0.59      0.59      9053\n",
      "weighted avg       0.60      0.60      0.59      9053\n",
      "\n",
      "{'C': 5, 'penalty': 'l2', 'solver': 'sag'}\n"
     ]
    }
   ],
   "source": [
    "embeddings = embeddings[:len(x_train)]\n",
    "parametros = {\n",
    "    'penalty': ['l1', 'l2'],\n",
    "    'C': [1, 3, 5, 6, 7, 8, 9, 10, 15, 20, 50],\n",
    "    'solver': ['newton-cg', 'sag', 'newton_cholesky', 'saga', 'libfgs']\n",
    "}\n",
    "\n",
    "logreg_grid = GridSearchCV(logreg, parametros, cv=5, n_jobs=-1)\n",
    "logreg_grid.fit(embeddings, y_train)\n",
    "previsoes_lgr_best = logreg_grid.predict(embeddings_teste)\n",
    "print(classification_report(y_test, previsoes_lgr_best))\n",
    "print(logreg_grid.best_params_)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "d43a2dbd7f2c85bd",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2023-10-25T04:30:19.784405800Z",
     "start_time": "2023-10-25T04:30:19.771201800Z"
    },
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "salvar_modelo(path='../resources/modelos/logreg_otimizado.pkl', modelo=logreg_grid.best_estimator_)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "3.11.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
